<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="uSync.BackOffice" Version="17.3.5" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" PrivateAssets="all" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Wayfinder.Engine" Version="0.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UmbracoPrism.Core\UmbracoPrism.Core.csproj" />
  </ItemGroup>

</Project>
