using System.Text;
using UmbracoPrism.Core.Persistence;
using static UmbracoPrism.Core.Services.MobileBundles.BundleText;

namespace UmbracoPrism.Core.Services.MobileBundles;

/// <summary>
/// The prose in the bundle: the README and the prompt for an AI coding agent that finishes the native build.
/// </summary>
internal static class BundleDocumentation
{
    internal static string BuildReadme(MobileBundleSettings settings)
    {
        var appName = settings.AppName;
        var startUrl = settings.StartUrl;
        var iconUrl = settings.IconUrl;
        var splashUrl = settings.SplashUrl;
        var biometricAuthEnabled = settings.BiometricAuthEnabled;
        var pushNotificationsEnabled = settings.PushNotificationsEnabled;

      var iconLine = string.IsNullOrWhiteSpace(iconUrl) ? "(not provided)" : iconUrl;
      var splashLine = string.IsNullOrWhiteSpace(splashUrl) ? "(not provided)" : splashUrl;

      var biometricSection = biometricAuthEnabled
          ? BundleTemplates.Read("readme-biometric.md")
          : string.Empty;

      var pushSection = pushNotificationsEnabled
          ? BundleTemplates.Read("readme-push.md")
          : string.Empty;

        return $$"""
# {{appName}} Mobile Shell

This bundle was generated by Umbraco Prism "Produce Mobile".

## Start URL

{{startUrl}}

## Quick start

1. Install dependencies:
   ```bash
   npm install
   ```
2. Run environment checks:

```bash
npm run doctor
```

3. Bootstrap iOS end-to-end:

```bash
npm run bootstrap:ios
```

Optional Android bootstrap:

```bash
npm run bootstrap:android
```

## Environment prerequisites

- Node.js 20+
- Xcode (for iOS)
- CocoaPods (for iOS)
- Android Studio + Android SDK (for Android)

Install CocoaPods on macOS:

```bash
brew install cocoapods
pod --version
```

## Common setup errors

- `[error] CocoaPods is not installed.`
  - Install CocoaPods, then rerun `npx cap add ios`.
- `[error] ios platform has not been added yet.`
  - Run `npx cap add ios` before `sync` or `open`.
- `[error] android platform has not been added yet.`
  - Run `npx cap add android` before `sync` or `open`.

### iOS localhost HTTPS (`NSURLErrorDomain -1202`)

If your `Start URL` is `https://localhost:<port>`, iOS simulator/device may reject the cert until it is trusted.

After `npx cap add ios`, run:

```bash
bash scripts/trust-ios-localhost-cert.sh
```

Then redeploy:

```bash
npx cap run ios
```

Notes:

- The script extracts the certificate from your current localhost endpoint and adds it to the booted simulator keychain.
- If no simulator is booted, open one first (Xcode or `xcrun simctl boot`).
- For real devices, use a LAN/tunnel/public HTTPS URL or install/trust your local CA profile on the device.

## Existing helper scripts

The bundle includes generated automation scripts:

- `scripts/doctor-mobile.sh` — validates tools, SDKs, and Start URL context.
- `scripts/bootstrap-ios.sh` — installs deps, adds/syncs iOS platform, applies localhost cert trust, and runs/opens iOS.
- `scripts/bootstrap-android.sh` — installs deps, adds/syncs Android platform, and runs/opens Android.
- `scripts/trust-ios-localhost-cert.sh` — imports localhost cert into booted iOS simulator keychain.
- `AGENT_PROMPT.md` — ready prompt to hand off setup troubleshooting to an AI coding agent.

You can still use low-level commands directly when needed:

```bash
npm run sync
npm run run:ios
npm run run:android
npm run open:ios
npm run open:android
```

## Runtime behavior

- Prism detects mobile mode using the appended user-agent marker.
- Tenant branding overrides are applied first.
- Mobile branding overrides are applied after tenant overrides.
- Generated config sets iOS `contentInset: 'always'` and `StatusBar.overlaysWebView: false` for safer default viewport behavior — `'always'` unconditionally reserves safe-area space (status bar/notch), fixing both a horizontal content-shift bug and a status-bar overlap that Capacitor's own default (`'automatic'`) and an earlier `'never'` attempt each caused in turn, on hosted content the app doesn't control (e.g. the Entra/OIDC login screen).
- App startup uses Capacitor top-level WebView loading of your Start URL.
- Generated config appends `prismMobile=1` to Start URL for server-side mobile detection.
- Prism mobile middleware can enforce in-WebView behavior for `target="_blank"` and `window.open`.
- A local fallback startup page is included in `www/index.html` if you choose to switch away from direct server URL mode.

## Entra authentication mode

- **Strict in-WebView mode:** keeps flows inside the WebView but may not satisfy all Entra/Conditional Access policies.
- **Compliance mode (recommended):** uses system browser auth session for Entra and can visually leave WebView.

Choose this explicitly per tenant/security policy. If strict in-WebView is mandatory, validate tenant policy and user journeys early.

## Customize mobile-specific UI

Use `www/mobile-overrides.css` as your starting point for mobile-scoped styles.
{{biometricSection}}{{pushSection}}
## Icons & Splash

- Icon source: {{iconLine}}
- Splash source: {{splashLine}}

Add final platform assets under the `resources/` folder and run Capacitor asset generation.
The `resources/mobile-assets.json` file stores the values entered in Backoffice for reference.
""";
    }

    internal static string BuildAgentPrompt(MobileBundleSettings settings)
    {
        var appName = settings.AppName;
        var startUrl = settings.StartUrl;
        var biometricAuthEnabled = settings.BiometricAuthEnabled;
        var pushNotificationsEnabled = settings.PushNotificationsEnabled;

        var biometricContext = biometricAuthEnabled
            ? """

## Biometric authentication

This bundle has biometric auth enabled. The bootstrap scripts inject platform entitlements automatically:

- **iOS:** `NSFaceIDUsageDescription` is added to `Info.plist`.
- **Android:** `USE_BIOMETRIC` permission is added to `AndroidManifest.xml`.

Plugins `@aparajita/capacitor-biometric-auth` and `@aparajita/capacitor-secure-storage` are in `package.json`
and auto-register via Capacitor discovery.

Simulator testing notes:
- iOS Simulator: `BiometricAuth.checkBiometry()` returns `isAvailable: false`. Use *Features → Face ID → Enrolled* for simulated match.
- Android Emulator: enroll a fingerprint with `adb emu finger touch 1`.
"""
            : string.Empty;

        var pushContext = pushNotificationsEnabled
            ? """

## Push notifications

This bundle has push notifications enabled via `@capacitor-firebase/messaging`. Before bootstrapping,
`resources/GoogleService-Info.plist` and `resources/google-services.json` must be present (get them from
Firebase Console). The bootstrap scripts then copy them into place, wire iOS entitlements/pbxproj/AppDelegate,
and let Android's Firebase Gradle plugin pick up `google-services.json` automatically. Real device tokens
only register once the app is signed with the `aps-environment: production` entitlement, so this cannot be
fully verified on the iOS Simulator — test on a physical device or a TestFlight build.
"""
            : string.Empty;

        return $$"""
# Prism Mobile Agent Prompt

You are helping bootstrap the generated "{{appName}}" Capacitor app.

## Goal

Get this app running in an emulator as quickly as possible.

## Deterministic sequence

1. Run `npm install`
2. Run `npm run doctor`
3. For iOS: run `npm run bootstrap:ios`
4. For Android: run `npm run bootstrap:android`

## Context

- Start URL: `{{startUrl}}`
- If localhost HTTPS fails on iOS (`NSURLErrorDomain -1202`), run `bash scripts/trust-ios-localhost-cert.sh`.
- If iOS/Android platform missing, run `npx cap add ios` / `npx cap add android` before sync/open.

## Troubleshooting hints

- iOS: verify Xcode + CocoaPods installed and simulator booted.
- Android: verify Android SDK/adb and an active emulator/device.
- Re-run `npm run doctor` after each fix.
{{biometricContext}}{{pushContext}}
""";
    }
}
