<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" PrivateAssets="all" />
    <PackageReference Include="Wayfinder" Version="0.2.0" />
    <PackageReference Include="Wayfinder.Engine" Version="0.2.0" />
    <PackageReference Include="Wayfinder.Umbraco" Version="0.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../UmbracoPrism.Core/UmbracoPrism.Core.csproj" />
    <ProjectReference Include="../UmbracoPrism.TestSite/UmbracoPrism.TestSite.csproj" />
    <ProjectReference Include="../UmbracoPrism.MockBusinessApp/UmbracoPrism.MockBusinessApp.csproj" Aliases="global,MockBusinessApp" />
  </ItemGroup>

</Project>
