@hostname = localhost
@port = 5163
@baseUrl = http://{{hostname}}:{{port}}

# PASTE YOUR JWT FROM TENANT A OR B HERE
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### Get Back-Office Status
# This simulates the Umbraco Front-end calling your API
GET {{baseUrl}}/api/backoffice/me
Authorization: Bearer {{token}}
Accept: application/json

###