<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="workflow-seeds\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="workflow-authored\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../UmbracoPrism.Core/UmbracoPrism.Core.csproj" />
    <ProjectReference Include="../UmbracoPrism.Shared/UmbracoPrism.Shared.csproj" />
    <ProjectReference Include="../UmbracoPrism.WorkflowRuntime/UmbracoPrism.WorkflowRuntime.csproj" />
    <ProjectReference Include="../UmbracoPrism.WorkflowRuntime.Api/UmbracoPrism.WorkflowRuntime.Api.csproj" />
    <ProjectReference Include="../UmbracoPrism.WorkflowRuntime.Mcp/UmbracoPrism.WorkflowRuntime.Mcp.csproj" />
    <ProjectReference Include="../UmbracoPrism.WorkflowEditor/UmbracoPrism.WorkflowEditor.csproj" />
  </ItemGroup>

</Project>
